config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do 
    post 'rt', to: 'tweets#rt'
    resources :likes, only: [:create, :update, :destroy]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
 

  
  root to: 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :bigint           not null, primary key
#  content    :text
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :retweets, class_name: "Tweet", foreign_key: "retweet_id"
  belongs_to :retweet, class_name: "Tweet", optional: true

  scope :tweets_for_me, -> (tweets_friends) { where( user_id: tweets_friends) }  

  validates :content, presence: true

  # Self hace referencia al lugar donde estamos situados
  def content_with_hashtag
    new_content = self.content.split(' ').map do |word|
      
      if word.include?('#')
        "<a href='/?search=#{word}'>#{word}</a>"
      else
        word
      end
    end
    new_content.join(' ').html_safe
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index search ]


  # GET /tweets or /tweets.json
  def index
    #@tweets = Tweet.page
    @tweet = Tweet.new
    if(user_signed_in?)
      tweets_friends = current_user.friends.pluck(:friend_id, current_user.id)
          
      if params[:search].blank?  
        @tweets = Tweet.tweets_for_me(tweets_friends).page(params[:page]).limit(49).order("id DESC")
        #@tweets = Tweet.where(user_id: current_user.id)
      else 
        @tweets = Tweet.where("content LIKE ?", "%" + params[:search] + "%").page(params[:page]).limit(49).order("id DESC") 
      end
    else 
      @tweets = Tweet.page(params[:page]).limit(49).order("id DESC") 
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    # tweet.likes.where(user: current_user)
    # @tweet.likes.where(user: current_user)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  def rt
    
    @tweet = Tweet.find(params[:tweet_id])
    @tweet.retweets.build(user_id: current_user.id, content: params[:content])
   
    if @tweet.save
      redirect_to root_path
    end
  end
  
  # GET /tweets/1/edit
  def edit
  end


  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

class Tweet
  scope :tweet_friends, -> { where() }
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.text_area :content, class:"form-control", placeholder:"Write your Tweet" %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit 'Write Tweet', class:"btn btn-primary btn-lg btn-block"  %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="container">

<% if user_signed_in? %>
  <h1 class="text-center">Crear Tweet</h1>

  <%= render 'form', tweet: @tweet %>
<% end %>

<h1 class="text-center">Tweets</h1>

<% @tweets.each do |tweet| %>
  <div class="card mb-3" style="max-width: 1250px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        
        
        <%= image_tag url_for(tweet.user.avatar ), class:"img-fluid" %>
      
      
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text"> <%= tweet.content_with_hashtag %> </p>

          
          <% if tweet.retweet_id.present? %>
            <div class="card">
              <% retweet = Tweet.find(tweet.retweet_id) %>
              <% user = User.find(retweet.user_id) %>
              <h6 class="card-header"> <%= user.username %> | Retweet </h6>
              <div class="card-body">
                <%= retweet.content %>
              </div>
            </div>
          <% end %>
          
          <br>
          <br>
          <% if tweet.likes.where(user_id: current_user).present? %>
            <i class="fas fa-heart"></i> 
          <% else %>
            <i class="far fa-heart"></i>
          <% end %>
          <strong> 
            <%=tweet.likes.count%> 
          </strong>

          <i class="fas fa-retweet"></i>
          <strong>
            <%= tweet.retweets.count %>
          </strong>
          

          <%= link_to 'Mostrar Tweet', tweet , class:"btn btn-primary"%>
          <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-primary" %>
          <%= link_to 'Destroy', tweet, class:"btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted text-center">
      <%= link_to time_ago_in_words(tweet.updated_at), tweet %> 
      |
      <%= tweet.id %>
    </div>
  </div>
<br>
<% end %>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center pagination-lg">
    <li class="page-item ">
     
    </li>

    <li class="page-item ">
      
    </li>
  </ul>
</nav>

</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="container">
  <p>
    <strong>Content:</strong>
    <%= @tweet.content_with_hashtag %>
    <%  user =  User.find(@tweet.user_id) %>
    <%= user.email %>
    <br>
    
    <% if @tweet.retweet_id.present? %>
      <div class="card">
        <% retweet = Tweet.find(@tweet.retweet_id) %>
        <% user = User.find(retweet.user_id) %>
        <h5 class="card-header"> <%= user.username %> | Retweet </h5>
        <div class="card-body">
          <p class="card-text">
            <%= retweet.content %>
          </p>
        </div>
      </div>
    <% end %>
  </p>

  <p>
  <% array_avatar = @tweet.likes %>
  <% array_avatar.each do |like| %>
    <% user = User.find(like.user_id) %>
    <%= image_tag url_for(user.avatar ), height:100, width:100 %> 
  <% end %>
  </p>

  <p>
    <%= time_ago_in_words(@tweet.updated_at) %>
  </p>

  <% current_tweet = @tweet.likes.where(user_id: current_user) %>

  <div class="form-group">
  <% if current_tweet.present? %>
    <%= form_with url: tweet_like_path(@tweet, current_tweet.first), method: :delete do |form| %>
      <%= form.submit 'No me gusta', class:"btn btn-primary" %>
    <% end %>
  <% else %> 
    <%= form_with url: tweet_likes_path(@tweet) do |form| %>
      <%= form.submit 'Me gusta', class:"btn btn-primary" %>
    <% end %>
  <% end %>
  </div>

  <div class="form-group">
    <%= form_with url: tweet_rt_path(@tweet), method: :post do |form| %>
      <%= form.text_field :content, class:"form-control" %>
      <br>
      <%= form.submit 'Dar Retweet', class:"btn btn-primary" %>
    <% end %>
  </div>

  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path %>
</div>